### ISSUE TITLE
TypeError reactFinalForm.withReactFinalForm is not a function

### ISSUE THREAD

**Issue by vladbesson** [final-form/react-final-form-arrays#55]
Looks like react-final-form-arrays v2.0.1 not working with react-final-form v3.6.7 (react-final-form-arrays v1 works good)

### Sandbox Link
https://codesandbox.io/s/vn1y5nrpv5

**Comment by ooflorent** [comment]
This is expected.
From the changelog:

> Upgraded to new React v16.3 Context API, so react-final-form@4.0.0 is a required peer dependency.

**Comment by erikras** [comment]
Yes, what @ooflorent said.

---

Hey, @ooflorent! Long time no chat. 👋

**Comment by Nuruddinjr** [comment]
I have this error with Typescript, CRA 2, and  react final form arrays v2.0.1, and final form 4.x
